GUACAMOLE-2003: Missing clipboard UI options for Kubernetes
apache/guacamole-client pull request #1037
Opened 2024-12-04 15:36 UTC by eugen-keeper

The pull request changes conflicts with GUACAMOLE-2002 and will require manual correction after applying that PR.

2024-12-05 17:30 UTC, mike-jumper requested changes
LGTM, but this should probably be merged to `patch` and not `main`.

@eugen-keeper I can edit the PR merge base here, but you will need to rebase.

2025-01-14 22:26 UTC, mike-jumper approved these changes

2025-01-15 19:34 UTC, eugen-keeper commented
Sorry... accidentally requested a review again

2025-01-20 17:32 UTC, mike-jumper approved these changes

2025-01-20 17:32 UTC, merged