add Docker secrets support for LDAP properties
apache/guacamole-client pull request #521
Opened 2020-06-11 19:05 UTC by ss10sb

Added _FILE for:

- LDAP_SEARCH_BIND_DN
- LDAP_SEARCH_BIND_PASSWORD
- LDAP_USER_BASE_DN
- LDAP_CONFIG_BASE_DN
- LDAP_GROUP_BASE_DN

Added SSL certificate support via LDAP_SSL_CERT_FILE (eg /run/secrets/ldap_cert) with keytool import for the file.  It could probably use an exists check but it works :)

2020-06-11 19:49 UTC, necouchman commented
@ss10sb: Thank you for the contribution, appreciate it.  Per our standard procedures, all pull requests need to be associated with a JIRA issue, and tagged with that.  Please see:

http://guacamole.apache.org/open-source/

2020-06-11 19:58 UTC, ss10sb commented
[GUACAMOLE-1099](https://issues.apache.org/jira/browse/GUACAMOLE-1099)

2020-10-31 12:46 UTC, necouchman requested changes

2020-10-31 12:46 UTC, necouchman commented on guacamole-docker/bin/start.sh
> +    if [ -n "$LDAP_USER_BASE_DN_FILE" ]; then
Is there a particular reason to include the various DNs in the Docker secrets support? I understand for password, and possibly for username, but it doesn't seem like an LDAP DN is all that sensitive a value that it needs to be protected??

2020-10-31 12:46 UTC, necouchman commented on guacamole-docker/bin/start.sh
> +    if [ -n "$LDAP_SSL_CERT_FILE" ]; then
I'm on the fence about this - I certainly don't have any problem supporting this functionality, but I'm not sure its entirely in scope of this particular change??

2020-10-31 18:19 UTC, mike-jumper reviewed
Reading the environment variable `FOO` from the file `FOO_FILE` feels like the sort of thing that would be best accomplished through changes to `set_optional_property` and `set_property`, rather than repeated `if` checks.

2021-05-13 21:25 UTC, necouchman commented
@ss10sb A handful of requests for changes, here - any chance you can polish this up so we can move forward with this? Also, there's a conflict, now, that needs to be resolved.

2021-05-19 18:27 UTC, ss10sb commented
> @ss10sb A handful of requests for changes, here - any chance you can polish this up so we can move forward with this? Also, there's a conflict, now, that needs to be resolved.

We're no longer using Guacamole + Docker. Sorry!

2021-05-27 20:39 UTC, closed without merging