GUACAMOLE-1291: Add Korean language support
apache/guacamole-client pull request #604
Opened 2021-04-21 18:41 UTC by OctopusET

Add korean support.

2021-04-22 00:48 UTC, OctopusET commented
Hello, I just squashed every commit. 
Sorry for confusing commits. I try to make commit more meaningful, and reasonable. 

If co-author things should be removed I will do it.

2021-04-22 00:53 UTC, necouchman commented
> If co-author things should be removed I will do it.

I'm in favor of keeping co-authors as it gives credit to people who've worked on the code, so I don't think you need to remove that, so long as it doesn't interfere with meaningful commit messages :-)

2021-04-22 01:06 UTC, OctopusET commented
I want to let them co-authors. They made an effort for this translations.

2021-04-30 11:51 UTC, OctopusET commented
Added missing translation from extensions.

2021-05-02 12:34 UTC, OctopusET commented
Update ko.json to 1.3.0.
I'm sorry if updating commit is annoying.

@necouchman  is there anything should I do?

2021-05-02 12:53 UTC, necouchman commented
@OctopusET: Force pushing the commit is fine, no issues with that. I'll try to review, soon, and make sure it looks okay.

2021-05-11 21:50 UTC, OctopusET commented on extensions/guacamole-auth-radius/src/main/resources/translations/ko.json
> +}
"Backend" can be translated, but writing in english is better. So, I will remove ko.json and restore guac.manifest.json

2021-05-12 12:40 UTC, necouchman commented
> Then should I remove every lines that reference another lines?

I believe so, yes. @mike-jumper can you confirm?

> and should I remove lines like ("FIELD_OPTION_BACKSPACE_EMPTY" : "",)? Even these kind line should be empty?

Again, yes, I believe you can leave off empty lines.

2021-05-12 14:10 UTC, OctopusET commented
@necouchman Okay I will remove all.

2021-05-12 15:25 UTC, OctopusET commented
Removed unnecessary lines as @necouchman refers.

2021-05-13 17:10 UTC, necouchman requested changes
Just a couple of extra commas that need to be removed in the main translation, and I think it'll be good.

2021-05-13 17:10 UTC, necouchman commented on guacamole/src/main/webapp/translations/ko.json
> +        "TABLE_HEADER_SESSION_USERNAME"        : "사용자 이름",
Extra comma needs to be removed.

2021-05-13 17:10 UTC, necouchman commented on guacamole/src/main/webapp/translations/ko.json
> +        "TEXT_CONFIRM_DELETE"   : "연결을 삭제한 후에는 복원할 수 없습니다. 이 연결을 삭제하겠습니까?",
Extra comma needs to be removed.

2021-05-13 18:25 UTC, OctopusET commented
@necouchman commas removed. Sorry I didn't notice them.

2021-05-13 18:46 UTC, necouchman approved these changes
Okay, good as far as I can tell. Merge here momentarily.

2021-05-13 18:47 UTC, merged

2021-05-13 19:01 UTC, OctopusET commented
Thank you for review.