Adds SKIP_IF_UNAVAILABLE in options
apache/guacamole-client pull request #658
Opened 2021-11-26 15:25 UTC by kevinimbrechts

Adds properties to guacamole.process wich configure other options (like skip-if-unavailable)

2021-11-26 19:10 UTC, necouchman commented
Thanks, @kevinimbrechts. This will need to be associated with a Jira issue and tagged appropriately before we will merge it.

2021-11-26 23:40 UTC, kevinimbrechts commented
Hi @necouchman. Yes sorry. Is it ok now ? Thanks.

2021-11-27 05:47 UTC, mike-jumper requested changes

2021-11-27 05:47 UTC, mike-jumper commented on guacamole-docker/bin/start.sh
> +## Adds properties to guacamole.process wich configure other
Some typos here:

* "guacamole.properties"
* "which"

2021-11-27 05:47 UTC, mike-jumper commented on guacamole-docker/bin/start.sh
> +## options
I think "other options" is a bit too vague here. It's unclear from reading the documentation for `associate_other()` exactly which configuration properties are in scope of the function. If the idea is that `associate_other()` covers any properties that are not tied to a specific extension, then I think that should be specified here.

Alternatively, there is already a section devoted to the few options that do not relate to an extension:

https://github.com/apache/guacamole-client/blob/c143c7cb5c73bcae51a4576c3bbe7d1d76ef7620/guacamole-docker/bin/start.sh#L794-L796

Simply placing the relevant call to `set_optional_property()` there may be better and simpler.

2021-11-27 05:47 UTC, mike-jumper commented on guacamole-docker/bin/start.sh
> +# Associate other keys
What is meant by "keys" here?

2021-11-29 09:17 UTC, kevinimbrechts commented
Hi @mike-jumper.
Thank you for the review.
I corrected typos and change du function name to associate_general_options. I added a better description.

Personally, I prefer to keep the function. Maybe placing guacd-hostname and guacd-port into associate_general_options is a good idea?
Let me know and I will adapt accordingly.
Thanks

2023-03-14 17:40 UTC, necouchman commented
Closing this, as this option was added by #794.

2023-03-14 17:40 UTC, closed without merging