GUACAMOLE-1261: Escape strings used to generate URLs for user, groups, and connections.
apache/guacamole-client pull request #666
Opened 2021-12-20 03:24 UTC by necouchman

This pull request implements an AngularJS filter - `escape` - for escaping special characters in strings that will end up as part of a URL, and then implements the `escape` on the user, group, and connection links so that users and groups that contain special characters will be correctly interpreted, resolving the bug in the associated Jira issue.

2021-12-23 00:51 UTC, mike-jumper requested changes
🍝

2021-12-23 00:51 UTC, mike-jumper commented on guacamole/src/main/frontend/src/app/index/filters/escapeFilter.js
> + * A filter for transforming an object into an array of all non-inherited
Copypasta from the other filter? ;)

2021-12-23 21:35 UTC, necouchman commented on guacamole/src/main/frontend/src/app/index/filters/escapeFilter.js
> + * A filter for transforming an object into an array of all non-inherited
yum.

2021-12-23 21:38 UTC, necouchman commented on guacamole/src/main/frontend/src/app/index/filters/escapeFilter.js
> + * A filter for transforming an object into an array of all non-inherited
Fixed via rebase.

2021-12-24 22:46 UTC, mike-jumper approved these changes

2021-12-24 22:51 UTC, merged

2021-12-24 22:55 UTC, mike-jumper commented
BTW, I just noticed:

![image](https://user-images.githubusercontent.com/4632905/147373757-6953c71b-2391-4a42-a898-0f7df7719bd2.png)

😈 

That explains the unsettling screaming I heard as I clicked "merge".